### ISSUE TITLE
object 'mstl' is not exported by 'namespace:forecast'

### ISSUE THREAD

**Issue by kairos35** [robjhyndman/tscompdata#1]
Hi, 
tried to install tscompdata using devtools::install_github("robjhyndman/tscompdata").
Get the following error message "Error : object 'mstl' is not exported by 'namespace:forecast'"
My R-version is  3.4.3 (2017-11-30); 
To be on the save side, I reinstalled your forecast package using install.packages('forecast', dependencies = TRUE)

Am grateful for any advice how to properly install your new time series package. Thanks a million.

**Comment by robjhyndman** [comment]
You need the github version of the forecast package.
